config/routes.rb
LinkedListBlog::Application.routes.draw do

  root 'home#index'

  post 'posts/:post_id/comments/' => 'comments#create', as: :comments_create
  delete 'posts/:post_id/comments/:id' => 'comments#delete', as: :comments_delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  def next
    return nil if self.next_id == 0

    Comment.find(self.next_id)
  end

  def append(comment)
    if self.next
      self.next.append(comment)
    else
      self.next = comment
    end
  end

  def remove(id)
    if self.next
      if self.next.id == id
        self.next = self.next.next
      else
        self.next.remove(id)
      end
    end
  end

  def to_ary
    if self.next
      [self] + self.next.to_ary
    else
      [self]
    end
  end

  private

  def next=(comment)
    return self.update!(next_id: 0) if not comment

    self.update!(next_id: comment.id)
  end
end

# Don't modify this
require "#{Rails.root}/lib/extensions/active_record/relation/explicit_addressing"
::ActiveRecord::Relation::ActiveRecord_Relation_Comment.send(:include,
    Extensions::ActiveRecord::Relation::ExplicitAddressing)

app/models/post.rb
class Post < ActiveRecord::Base

  def comments
    Comment.find(comments_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def create
    comment = Comment.create!(create_params)
    @post.comments.append(comment)
    redirect_to '/'
  end

  def delete
    @post.comments.remove(params[:id].to_i)
    redirect_to '/'
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def create_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # Display our latest blog post
    @post = Post.all.first || Post.new

    # For now get all of the comments
    # maybe implement paging later?
    @comments = @post.comments.to_ary || []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="post" class="post">
  <div class="post-header">
    <h1><%= @post.title %></h1>
  </div>
  <div class="post-body">
    <p><%= @post.body %></p>
  </div>
  <div class="post-comments">
    <% @comments.each do |c| %>
      <div class="post-comment-header">
        <h4><%= c.name %></h4>
      </div>
      <div class="post-comment-body">
        <p><%= c.body %></p>
      </div>
      <div class="post-comment-controls">
        <%= button_to "Delete Comment", comments_delete_url(id: c.id, post_id: @post.id),
                                        method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  </div>
  <div class="post-comments-controls">
    <%= form_for Comment.new, url: comments_create_url(post_id: @post.id) do |f| %>
      <%= f.label :name %>:
      <%= f.text_field :name %><br />
      <%= f.label :body, "Comment" %>:
      <%= f.text_area :body %><br />
      <%= f.submit "Post Comment" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkedListBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>